version: '3.8'

services:
  tailscale-funnel-manager:
    build: .
    container_name: tailscale-funnel-manager
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./tailscale:/var/lib/tailscale
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    privileged: true
    environment:
      - TZ=America/Sao_Paulo
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge